In [ ]:
## use Ax + b to see which matrix makes the classification rates greatest

In [ ]:
import os;
from google.colab import drive
drive.mount('/content/drive', force_remount=True);
path = "/content/drive/Shared drives/Computational Optics Group/Yizhou_Lu_FLIM/Eigen Face";
os.chdir(path);


import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

plt.style.use("seaborn-ticks")

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, classification_report

import warnings
warnings.filterwarnings('ignore')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
## convert the dataframe into np.array
df = pd.read_csv('face_data.csv');
X = df.drop('target', axis=1);
X = X.values;
y = df['target'];
y = y.values;

In [ ]:
from sklearn import linear_model;

X_train, X_test, y_train, y_test = train_test_split(X, y);

reg = linear_model.Ridge(alpha = 0);
reg.fit(X_train,y_train);
predictions = reg.predict(X_test);
print(np.sum(np.array(y_test) == np.round(predictions))/len(y_test))

0.07


In [ ]:
reg.predict(X[10:11,:])

array([19.57981478])

In [ ]:
y[10]

1

In [ ]:
predictions - y_test

array([-12.13652499,  -5.78835942,   0.11933407,   7.11748284,
        10.38698081,   9.35927315, -11.07884659,  -0.20141584,
        -1.8405963 ,  -3.70379423,   2.39086878,  -1.46219177,
        13.19024955,   5.96297482,  -1.91392555,  -0.0724055 ,
         3.04526471,   1.41005654,  -7.85928376,  10.54011001,
         1.93202787,  -2.20611713,   1.71247287,  -0.77140195,
         5.61131227,   4.91878267,  -4.32794048,  -8.52277616,
        -2.10763684,  14.24289456,   9.99924969,  -3.46311237,
        21.99758536,  11.713077  ,   6.47118035,   6.5096867 ,
        -4.60097903,   2.60099896,  -4.3148039 ,  -0.20259535,
         1.98606959,  -4.39679113,   4.85800655,  -5.72558977,
        -1.90640124,  10.35333499,  -2.35669316,   1.79238959,
       -14.5122539 ,   1.32329701,  -7.48786392,   2.9572344 ,
        -3.18218918,   1.60293333,  11.39523372,  12.31881412,
        -1.42434335,  -0.56672877,   3.59758519,   0.77666053,
        -3.65738   ,   6.28741142,  18.57981478,  -0.19

In [ ]:
y_test

array([ 9, 11,  7, 26, 39, 27, 37, 36,  5, 32, 11, 32, 20,  9, 13,  7, 24,
       37, 15, 36, 36,  2,  6, 10, 24, 24, 20, 34, 15, 30,  4, 19,  0, 25,
       19, 32,  3, 21, 10, 22, 27, 31,  6, 31, 11, 22, 22, 29, 33, 10, 17,
       30, 37, 30,  7, 36, 27, 18, 13, 14, 10,  6, 16, 25, 35,  4, 28, 23,
        1,  9, 27, 18, 10,  8, 22, 23, 23,  1,  1, 16, 12,  3, 39, 34, 39,
        2,  0,  3, 11, 12, 31, 28, 18, 25, 31, 10, 16, 15, 22, 20])

In [ ]:
sum(reg.coef_)

-99.7168828331529

In [ ]:
xx = np.array([1,2,3,4,5,6,7,8]).reshape(-1,1);
yy = np.array([1,2,3,4,5,6,7,8]);
reg.fit(xx,yy)

Ridge(alpha=1e-05, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
reg.predict(np.array([[11],[0],[-2]]))

array([ 1.09999985e+01,  1.07142832e-06, -1.99999845e+00])

In [ ]:
 reg.fit([[0, 0], [1, 1]], [0, 1])

Ridge(alpha=1e-05, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)